// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkfdVidlHTq4J79yC7b2jf_q7VpGTWcFs',
    appId: '1:737721176075:web:cd77f87eb802b10a3d770e',
    messagingSenderId: '737721176075',
    projectId: 'emart-34256',
    authDomain: 'emart-34256.firebaseapp.com',
    storageBucket: 'emart-34256.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlfzsbqrk0XU5dA2h84U708_eQE-jq-DI',
    appId: '1:737721176075:android:6e5d869584dbd14e3d770e',
    messagingSenderId: '737721176075',
    projectId: 'emart-34256',
    storageBucket: 'emart-34256.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLPyWUt_vWdqHLCi6lhdes_omBvOkOIm0',
    appId: '1:737721176075:ios:e6bf457452c112fd3d770e',
    messagingSenderId: '737721176075',
    projectId: 'emart-34256',
    storageBucket: 'emart-34256.appspot.com',
    iosBundleId: 'com.example.emartSeller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLPyWUt_vWdqHLCi6lhdes_omBvOkOIm0',
    appId: '1:737721176075:ios:e6bf457452c112fd3d770e',
    messagingSenderId: '737721176075',
    projectId: 'emart-34256',
    storageBucket: 'emart-34256.appspot.com',
    iosBundleId: 'com.example.emartSeller',
  );
}
